"""empty message

Revision ID: 3bf346f90659
Revises: 83c888b0cc44
Create Date: 2017-04-08 20:03:28.646214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf346f90659'
down_revision = '83c888b0cc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personalinfo',
    sa.Column('dummy_ID', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('passwd', sa.String(length=20), nullable=True),
    sa.Column('login_id', sa.String(length=20), nullable=True),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('dummy_ID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personalinfo')
    # ### end Alembic commands ###
