"""empty message

Revision ID: 83c888b0cc44
Revises: 3d0be65b6103
Create Date: 2017-04-08 19:55:25.787747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c888b0cc44'
down_revision = '3d0be65b6103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('login_ID', sa.String(length=20), nullable=True),
    sa.Column('admin_pwd', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('supplier',
    sa.Column('supplier_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('supplier_id', 'first_name', 'last_name')
    )
    op.create_table('aboutorder',
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('ship_via', sa.String(length=20), nullable=True),
    sa.Column('shipper_ID', sa.String(length=20), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.String(length=20), nullable=False),
    sa.Column('nop', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.String(length=20), nullable=False),
    sa.Column('quantity_pu', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=20), nullable=True),
    sa.Column('stock_units', sa.Integer(), nullable=True),
    sa.Column('unit_weight', sa.Float(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('product_description', sa.String(length=30), nullable=True),
    sa.Column('supplier_ID', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('billinginfo',
    sa.Column('billing_id', sa.String(length=40), nullable=False),
    sa.Column('credit_card_pin', sa.Integer(), nullable=True),
    sa.Column('credit_card_num', sa.Integer(), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('billing_addr', sa.String(), nullable=True),
    sa.Column('credit_card_expiry', sa.Date(), nullable=True),
    sa.Column('customer', sa.String(length=20), nullable=True),
    sa.Column('aboutorder', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aboutorder'], ['aboutorder.order_id'], ),
    sa.ForeignKeyConstraint(['customer'], ['customer.customer_id'], ),
    sa.PrimaryKeyConstraint('billing_id')
    )
    op.create_table('orderdetails',
    sa.Column('useless_ID', sa.Integer(), nullable=False),
    sa.Column('order_num', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=20), nullable=True),
    sa.Column('aboutorder', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aboutorder'], ['aboutorder.order_id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('useless_ID')
    )
    op.create_table('shipper',
    sa.Column('shipper_id', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=20), nullable=True),
    sa.Column('aboutorder', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aboutorder'], ['aboutorder.order_id'], ),
    sa.PrimaryKeyConstraint('shipper_id')
    )
    op.create_table('trackinginfo',
    sa.Column('tracking_id', sa.String(length=20), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('product', sa.String(length=20), nullable=True),
    sa.Column('aboutorder', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aboutorder'], ['aboutorder.order_id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trackinginfo')
    op.drop_table('shipper')
    op.drop_table('orderdetails')
    op.drop_table('billinginfo')
    op.drop_table('product')
    op.drop_table('cart')
    op.drop_table('aboutorder')
    op.drop_table('supplier')
    op.drop_table('category')
    op.drop_table('admin')
    # ### end Alembic commands ###
