"""empty message

Revision ID: b67540c120d1
Revises: bfe42bbe0f5b
Create Date: 2017-04-08 20:07:40.682887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67540c120d1'
down_revision = 'bfe42bbe0f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['loginid'])
    op.create_unique_constraint(None, 'customer', ['passwd'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
